environment:
  matrix:
  # node.js
  - nodejs_version: "0.10"
  - nodejs_version: "0.11"
  - nodejs_version: "0.12"    
  - nodejs_version: "4.0"
  # io.js
  - nodejs_version: "1.0"
  # Windows isn't fully supported by dockerlint, so allow failing all the tests.
  allow_failures:
    - nodejs_version: "0.10"
    - nodejs_version: "0.11"
    - nodejs_version: "0.12"
    - nodejs_version: "1.0"
    - nodejs_version: "4.0"      

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
  